sensor_kit_base_link:
  olei_back_base_link:
    x: 0.69554
    y: -0.258
    z: -1.587
    roll: 0.0
    pitch: 0.0
    yaw: -0.78
  olei_front_base_link:
    x: -0.246
    y: 0.258
    z: -1.587
    roll: 0.0
    pitch: 0.0
    yaw: 2.35
  rslidar:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
